name: Add QA link to issues on successful build
permissions: read-all

on:
  pull_request:
    types:
      - opened

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.event.pull_request.head.repo.full_name == 'mi6/ic-ui-kit'
    steps:
      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: extract_branch

      - uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc #v2.8.2
        with:
          message: |
            View your branch deployment here: https://mi6.github.io/ic-ui-kit/branches/${{ steps.extract_branch.outputs.branch }}/web-components
            View your React branch deployment here: https://mi6.github.io/ic-ui-kit/branches/${{ steps.extract_branch.outputs.branch }}/react
          message-id: "branch-deployment"
